# ---
- hosts: localhost
  gather_facts: no
  tasks:
      - name: Check the current system date.
        command: date
        register: date
      - name: Print the current system date.
        debug: var=date.stdout
      - name: List conents in directory
        shell: ls
