language: bash

sudo: required

os:
    - osx
    - linux

before_script:
    - git clone https://github.com/tallamjr/dotfiles.git

script:
    - bash provisionNIX.sh
    # - travis_wait 30 bash provisionNIX.sh
