language: bash

sudo: required

os:
    - osx
    - linux

before_script:
    - curl -fsSL https://raw.githubusercontent.com/tallamjr/dotfiles/master/provisionNIX.sh

script:
    - bash provisionNIX.sh
