local keymap = vim.keymap -- for conciseness

-- abbreviations
keymap.set("ia", "WQ", "wq")
keymap.set("ia", "teh", "the")
keymap.set("ia", "sun", "Sun")
keymap.set("ia", "universe", "Universe")
keymap.set("ia", "eqaution", "equation")
-- emoji shortcuts
keymap.set("ia", ":bomb:", "💣")
keymap.set("ia", ":book:", "📖")
keymap.set("ia", ":bulb:", "💡")
keymap.set("ia", ":grimm:", "😬")
keymap.set("ia", ":computer:", "💻")
keymap.set("ia", ":email:", "📧")
keymap.set("ia", ":happy_face:", "🙂")
keymap.set("ia", ":info:", "ℹ️")
keymap.set("ia", ":link:", "🔗")
keymap.set("ia", ":nerd_face:", "🤓")
keymap.set("ia", ":pencil:", "✏️")
keymap.set("ia", ":pill:", "💊")
keymap.set("ia", ":point_right:", "👉🏼")
keymap.set("ia", ":point_down:", "👇🏼")
keymap.set("ia", ":point_up:", "👆🏼")
keymap.set("ia", ":point_left:", "👈🏼")
keymap.set("ia", ":pushpin:", "📍")
keymap.set("ia", ":sad_face:", "☹️")
keymap.set("ia", ":see_no_evil:", "🙈")
keymap.set("ia", ":sweat:", "😅")
keymap.set("ia", ":telephone:", "☎️")
keymap.set("ia", ":telescope:", "🔭")
keymap.set("ia", ":tick:", "✅")
keymap.set("ia", ":thumbsup:", "👍🏼")
keymap.set("ia", ":warning:", "⚠️")
keymap.set("ia", ":wip:", "🚧")
keymap.set("ia", ":wrench:", "🔧")
keymap.set("ia", ":writing:", "🏼")
keymap.set("ia", ":x:", "❌")
keymap.set("ia", ":??:", "❔")
