name: x
channels:
  - conda-forge
dependencies:
  - pip
  - python=3.12
  - pip:
    - black
    - neovim
    - pytest
    - pytest-cov
    - pytest-subtests
    - pep517
    - twine
    # - -r requirements.txt
