---
- name: Get applications to be install with Homebrew
  shell: "cat ~/dotfiles/brew/.brewcasklist"
  register: brewcasklist

- name: Install applications listed in brewcasklist.txt
  shell: "brew cask install {{ item }}"
  with_items: "{{ brewcasklist.stdout_lines|default([]) }}"
  ignore_errors: yes

#- name: Get applications to be install with Homebrew-Cask
#- shell: "cat ~/dotfiles/brew/.brewcasklist"
#- register: brewcasklist
#
#- name: Install applications listed in brewcasklist.txt
#- homebrew_cask: name={{ item }} state=latest install_options: 'appdir=/Applications'
#- with_items:
#    - "{{ brewcasklist.stdout_lines }}"
