name: Smoke

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, macos-10.15, ubuntu-latest]
    steps:
     - uses: actions/checkout@v1
     - run: echo ${{matrix.os}}
       env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true

     - name: Check environment
       shell: bash -l {0}
       run: |
         echo $PWD
         ls -la ${{ github.workspace }}
         echo $HOME

     - name: Run Installation
       shell: bash -l {0}
       run: |
         bash ./install.sh
